### ISSUE TITLE
Broken for submodules

### ISSUE THREAD

**Issue by kankaristo** [jakesankey/line-diff-details#12]
line-diff-details hasn't been working for a long time, and I miss the functionality. :(

Atom's error popup points to #3, but since that issue and other similar issues are closed, I thought I'd open a new one. The error happens for edited, added and deleted lines.

Stack trace below:
```
TypeError: Cannot read property 'length' of null
    at LineDiffWorker.findDiffForLine (/home/sami/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:77:9)
    at LineDiffWorker.calculateDiffDetails (/home/sami/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:87:20)
    at HTMLDivElement.<anonymous> (/home/sami/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:32:24)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom-beta/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom-beta/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

Atom 1.3.0-beta5, line-diff-details 1.1.3, Ubuntu 15.10.

**Comment by kankaristo** [comment]
I just noticed that this only seems to happen for Git submodules, not the main repo.

**Comment by kankaristo** [comment]
The below change fixes the package for Git submodules.

lib/line-diff-worker:64
```coffee
     findFileDiffs: ->
         activePath = @editor.getPath()
         if process.platform is 'win32'
             repo = r for r in atom.project.getRepositories() when activePath.indexOf(r?.repo.workingDirectory.replace(/\//g, "\\")) != -1
         else
             repo = r for r in atom.project.getRepositories() when activePath.indexOf(r?.repo.workingDirectory) != -1
         return [] if not repo?
         fileRepo = repo.getRepo(activePath)
         activeEditorText = @editor.getBuffer().getText()
-        return fileRepo.getLineDiffDetails(repo.relativize(activePath), activeEditorText)
+        relativePath = activePath.substring(fileRepo.workingDirectory.length + 1)
+        return fileRepo.getLineDiffDetails(relativePath, activeEditorText)
```

`GitRepository::relativize()` seems to be broken for submodules (it always returns the path relative to the main repo, not the submodule). I opened an issue for it at https://github.com/atom/atom/issues/10373, but since `GitRepository::getRepo()` is private, you shouldn't even be able to access a submodule's `GitRepository`.

The above change does what the [docs](https://atom.io/docs/api/v1.3.3/GitRepository#instance-relativize) for `GitRepository::relativize()` say it should do, and it seems to fix `line-diff-details` for submodules. I haven't tested it very much yet (I'm on Linux, Windows paths are one thing that scare me).

**Comment by jakesankey** [comment]
Thanks. I am cutting a new release with this change..
