### ISSUE TITLE
Use same font?

### ISSUE THREAD

**Issue by peteruithoven** [jakesankey/line-diff-details#14]
With the current preview it's sometimes hard to see the difference. It might help to use the same font as the code. This way the code will line up with the code and it might be easier to spot differences. 
![screen shot 2016-01-07 at 17 13 08](https://cloud.githubusercontent.com/assets/523210/12175356/fb917fea-b561-11e5-9f23-2221d624f4e7.png)

**Comment by laughedelic** [comment]
+1

**Comment by peteruithoven** [comment]
Maybe the new Block decorations system can be used for this? 
http://blog.atom.io/2016/02/03/introducing-block-decorations.html

**Comment by laughedelic** [comment]
@peteruithoven https://github.com/jakesankey/line-diff-details/issues/15 :wink:

**Comment by peteruithoven** [comment]
Ah, nice. I'll close this then.
