### ISSUE TITLE
Deprecated selector in `line-diff-details/styles/line-diff-details.less`

### ISSUE THREAD

**Issue by kankaristo** [jakesankey/line-diff-details#28]
In `line-diff-details/styles/line-diff-details.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .line-diff-added` => `atom-text-editor.editor .line-diff-added`

* `atom-text-editor::shadow .line-diff-modified` => `atom-text-editor.editor .line-diff-modified`

* `atom-text-editor::shadow .line-diff-removed` => `atom-text-editor.editor .line-diff-removed`

* `atom-text-editor::shadow .line-diff-marker` => `atom-text-editor.editor .line-diff-marker`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by UziTech** [comment]
this should be fixed by pull request #34

**Comment by RTSchriner** [comment]
Any update on this? - My OCD

**Comment by UziTech** [comment]
@jakesankey The pull request was merged for this. Any timeline for an apm release?

**Comment by jakesankey** [comment]
Sorry I hadn't gotten to this yet. Should be published now.
