### ISSUE TITLE
Disables navigation to preferences from the menu

### ISSUE THREAD

**Issue by christreanor** [jakesankey/line-diff-details#41]
After installing this plug-in it disables the ability to navigate to the preference page from the menu. the shortcut still works though (cmd,)

**Comment by jakesankey** [comment]
I just tried with a fresh atom install and with this plugin installed, I am not able to reproduce this. I am able to use the `Preferences` option in the Atom menu, `cmd+,` keyboard shortcut, and also get there via the command pallet.
