### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MattiJarvinen-BA** [jakesankey/line-diff-details#7]
[Enter steps to reproduce below:]

1. Open a file with added lines
2. Click on line gutter to reveal diff on any change

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\matti_000\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:44

TypeError: Cannot read property 'length' of undefined
  at LineDiffWorker.decorateDiffMarkers (C:\Users\matti_000\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:44:67)
  at HTMLDivElement.<anonymous> (C:\Users\matti_000\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:34:14)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\matti_000\.atom\packages\line-diff-details\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (C:\Users\matti_000\.atom\packages\line-diff-details\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "git-log",
      "git-control",
      "show-origin",
      "symbols-tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
line-diff-details, v1.1.2

# Dev
No dev packages
```

**Comment by Dbuggerx** [comment]
Same happening here.

**Comment by mmcintyre123** [comment]
This is preventing the package from working at all in atom.  Can someone please fix.  Thanks!

**Comment by jakesankey** [comment]
Are any of you using Mac? I cannot reproduce this issue from my mac.

**Comment by mmcintyre123** [comment]
I'm using it in Windows, but I also use atom in Ubuntu and have no problem there.  But that is also a fork of the main project (see https://github.com/yuki-takei/atom-using-electron-chrome-42) so yuki-takei may have fixed the issue there.

Short answer seems to be, it's a problem with Atom in Windows.

**Comment by MattiJarvinen-BA** [comment]
Windows here as well.

**Comment by mmcintyre123** [comment]
I'm working more in Windows at the moment so I hope this can be fixed soon!  Great package, miss being able to use it ...

**Comment by hstitz-jku** [comment]
I got the same error on Windows 7 as well.

**Comment by jakesankey** [comment]
I will continue to look into this but I'm sorry, I am unable to debug this on Windows. I don't have access to a Windows machine currently. Whoever is willing and witnessing the issue, please feel free to investigate and I will happily merge any pull requests related to this issue.

**Comment by hstitz-jku** [comment]
I found the problem, but I don't know how to solve it. 

In LineDiffWorker.findFileDiffs it searches for the repo and fails in the path/directory comparison, because of the different directory separators "/" and "\" (see screenshot).

![atom-line-diff-worker](https://cloud.githubusercontent.com/assets/5851088/9056079/92055994-3a90-11e5-8570-12e3cf0747c6.png)

Does somebody know how to handle the paths correct?

**Comment by hstitz-jku** [comment]
Replacing the directory separator should do the trick. Please test on other OS too.

**Comment by mmcintyre123** [comment]
I added the fix (https://github.com/hstitz-jku/line-diff-details/commit/a5037f3cb9f91f095ca51fb9ebee6137ac87667c) to my local copy of atom.  Though I don't get an error popup now when I click the line where the change was made, instead of showing the option to "close, copy, revert", it shows  a popup of the text of the whole file.  See screenshot.
![atom line-diff-details bug](https://cloud.githubusercontent.com/assets/12388285/9062504/df1f7cfa-3a90-11e5-90c2-c0c4fb73e47a.png)

**Comment by hstitz-jku** [comment]
As far as I understood the code it will read the original file to find the changed lines. But I think @jakesankey knows more about this.

With the fix it looks like this for me (and works correct):
![atom-line-diff-change](https://cloud.githubusercontent.com/assets/5851088/9062581/a9fc9b74-3ac3-11e5-9abc-c0ef92e82e62.png)

**Comment by mmcintyre123** [comment]
And you're on Windows 7 and just changed that one line in lib/line-diff-worker.coffee? Strange!

**Comment by mmcintyre123** [comment]
Aha, so it sort of works now for txt files, but it doesn't work for me in .rb, .feature (cucumber), or .js files.  Also, clicking "revert" for a change in a txt files also adds a new line (which has to separately be reverted).  So it's buggy in general on Windows.

**Comment by jakesankey** [comment]
Please try v1.1.3 and let me know if it solved your issues.

**Comment by petepolack** [comment]
For me unfortunately it did not (OSX 10.10.3).

**Comment by rugk** [comment]
It works with Windows 7 here.

**Comment by littlebee** [comment]
I'm getting it on osx v 10.11,  line-diff-details v1.1.3.   Happens when I click in the left gutter to open the popup.
