### ISSUE TITLE
If changes are too large, you can not access to copy, close or revert buttons

### ISSUE THREAD

**Issue by romanfazulianov** [jakesankey/line-diff-details#8]
I have such issue when do refactoring. The window with changes becomes too big, so buttons and some text just will go out of the screen. No scroll, no shortcuts - so i can't quit this window and have to reopen the tab with the file again...

**Comment by jakesankey** [comment]
I'll take a look for the next release.. Thanks

**Comment by chamini2** [comment]
This is still happening, when a line is too long, it just goes all the way to the right, we need some sort of line wrapping.

**Comment by jakesankey** [comment]
Fixed with #22
